url: "https://flow.cgu.edu.tw/BPM/Default.aspx"

login:
  username: "your_account@cgu.edu.tw"
  password: "your_password"

schedule:
  scan_time: "08:30"
  timezone: "Asia/Taipei"
  weekdays_only: true
  late_grace_sec: 120
  auto_exit_after_last_job: true
  task_retry_once_sec: 120

browser:
  headless: false
  wait_timeout: 20

work_log_path: "./work_log.txt"

notification:
  line_token: ""

leave:
  leave_dates: []
  leave_shift_indexes_by_date:
    # "2026-03-31": [1, 2]
  reason_text: "請假(未出勤)"
  auto_submit: true
  click_retry_once_sec: 30

holiday:
  holiday_dates: []
  # example:
  #   - "2026-04-03"
  #   - "2026-04-06"
